import { definePackageConfig } from "../../tsdown.base";

export default definePackageConfig({
  entry: ["src/**/*.{ts,tsx}"],
  // CSS files aren't generated by tsdown — declare them statically so the
  // `./styles/*.css` subpath survives every rebuild.
  customExports: (exports) => ({
    ...exports,
    "./styles/*.css": "./src/styles/*.css",
  }),
});
